/*
 Highcharts JS v2.0.4 (2010-09-07)

 (c) 2009-2010 Torstein Hønsi

 License: www.highcharts.com/license
*/
(function(){function R(a,b){a||(a={});for(var c in b)a[c]=b[c];return a}function T(a){return a!==Ma&&a!==null}function pa(a,b,c){var d,e="setAttribute",f;if(typeof b=="string")if(T(c))a[e](b,c);else{if(a&&a.getAttribute)f=a.getAttribute(b)}else if(T(b)&&typeof b=="object")for(d in b)a[e](d,b[d]);return f}function nc(a){if(!a||a.constructor!=Array)a=[a];return a}function z(){var a=arguments,b,c;for(b=0;b<a.length;b++){c=a[b];if(T(c))return c}}function oc(a){var b="",c;for(c in a)b+=pc(c)+":"+a[c]+
";";return b}function Na(a,b){if(Yb)if(b&&b.opacity!==Ma)b.filter="alpha(opacity="+b.opacity*100+")";R(a.style,b)}function Fa(a,b,c,d,e){a=la.createElement(a);b&&R(a,b);e&&Na(a,{padding:0,border:fb,margin:0});c&&Na(a,c);d&&d.appendChild(a);return a}function Oc(){var a=wa.global.useUTC;Zb=a?Date.UTC:function(b,c,d,e,f,g){return(new Date(b,c,z(d,1),z(e,0),z(f,0),z(g,0))).getTime()};qc=a?"getUTCMinutes":"getMinutes";rc=a?"getUTCHours":"getHours";sc=a?"getUTCDay":"getDay";Pb=a?"getUTCDate":"getDate";
$b=a?"getUTCMonth":"getMonth";ac=a?"getUTCFullYear":"getFullYear";Pc=a?"setUTCMinutes":"setMinutes";Qc=a?"setUTCHours":"setHours";tc=a?"setUTCDate":"setDate";Rc=a?"setUTCMonth":"setMonth";Sc=a?"setUTCFullYear":"setFullYear"}function fd(a){wa=ma(wa,a);Oc();return wa}function gd(){return wa}function bc(a){cc||(cc=Fa(zb));a&&cc.appendChild(a);cc.innerHTML=""}function gb(a,b){var c=function(){};c.prototype=new a;R(c.prototype,b);return c}function hd(a,b,c,d){var e=wa.lang;a=a;var f=isNaN(b=Ya(b))?2:b;
b=c===undefined?e.decimalPoint:c;d=d===undefined?e.thousandsSep:d;e=a<0?"-":"";c=parseInt(a=Ya(+a||0).toFixed(f),10)+"";var g=(g=c.length)>3?g%3:0;return e+(g?c.substr(0,g)+d:"")+c.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(f?b+Ya(a-c).toFixed(f).slice(2):"")}function id(a){for(var b={x:a.offsetLeft,y:a.offsetTop};a.offsetParent;){a=a.offsetParent;b.x+=a.offsetLeft;b.y+=a.offsetTop;if(a!=la.body&&a!=la.documentElement){b.x-=a.scrollLeft;b.y-=a.scrollTop}}return b}function dc(){}function jd(a){function b(m,
i){function r(){var k=[],q;H=M=null;U=[];o(ta,function(s){q=false;o(["xAxis","yAxis"],function(B){if(s.isCartesian&&(B=="xAxis"&&L||B=="yAxis"&&!L)&&(s.options[B]==i.index||s.options[B]===Ma&&i.index===0)){s[B]=V;U.push(s);q=true}});if(!s.visible&&G.ignoreHiddenSeries)q=false;if(q){var y,C;if(!L){y=s.options.stacking;ec=y=="percent";if(y){C=k[s.type]||[];k[s.type]=C}if(ec){H=0;M=99}}if(s.isCartesian){o(s.data,function(B){var I=B.x,ga=B.y;if(H===null)H=M=B[nb];if(L)if(I>M)M=I;else{if(I<H)H=I}else if(T(ga)){if(y)C[I]=
C[I]?C[I]+ga:ga;B=C?C[I]:ga;if(!ec)if(B>M)M=B;else if(B<H)H=B;if(y)Za[s.type][I]={total:B,cum:B}}});if(/(area|column|bar)/.test(s.type)&&!L)if(H>=0){H=0;Tc=true}else if(M<0){M=0;Uc=true}}}})}function w(k,q,s){var y=1,C=0;if(s){y*=-1;C=Oa}if(Ab){y*=-1;C-=y*Oa}if(N===Ma)k=null;else if(q){if(Ab)k=Oa-k;k=k/hb+N}else k=y*(k-N)*hb+C;return k}function J(k,q,s){if(s){var y,C,B;y=w(k);var I;k=C=y+Bb;y=B=Ga-y-Bb;if(Y){y=ha;B=Ga-Cb;if(k<aa||k>aa+xa)I=true}else{k=aa;C=Ta-uc;if(y<ha||y>ha+qa)I=true}I||P.path(P.crispLine([$a,
k,y,Ja,C,B],s)).attr({stroke:q,"stroke-width":s}).add(Q)}}function K(k,q,s){k=tb(k,N);q=Lb(q,Z);var y=(q-k)*hb;J(k+(q-k)/2,s,y)}function D(k,q,s,y,C,B,I){var ga,pb,ea,Ua=i.labels;if(q=="inside")C=-C;if(ia)C=-C;q=pb=w(k+Db)+Bb;ga=ea=Ga-w(k+Db)-Bb;if(Y){ga=Ga-Cb-(ia?qa:0)+Va;ea=ga+C}else{q=aa+(ia?xa:0)+Va;pb=q-C}y&&P.path(P.crispLine([$a,q,ga,Ja,pb,ea],y)).attr({stroke:s,"stroke-width":y}).add(p);if(B&&Ua.enabled)if((k=kd.call({index:I,isFirst:k==fa[0],isLast:k==fa[fa.length-1],dateTimeLabelFormat:fc,
value:Pa&&Pa[k]?Pa[k]:k}))||k===0){q=q+Ua.x-(Db&&Y?Db*hb*(Ab?-1:1):0);ga=ga+Ua.y-(Db&&!Y?Db*hb*(Ab?1:-1):0);P.text(k,q,ga,Ua.style,Ua.rotation,Ua.align).add(p)}}function na(k,q){var s;ub=q?1:Ka.pow(10,ib(Ka.log(k)/Ka.LN10));s=k/ub;if(!q){q=[1,2,2.5,5,10];if(i.allowDecimals===false)if(ub==1)q=[1,2,5,10];else if(ub<=0.1)q=[1/ub]}for(var y=0;y<q.length;y++){k=q[y];if(s<=(q[y]+(q[y+1]||q[y]))/2)break}k*=ub;return k}function ua(){fa=[];var k,q=wa.global.useUTC,s=1E3/ab,y=6E4/ab,C=36E5/ab,B=864E5/ab,I=
6048E5/ab,ga=2592E6/ab,pb=31556952E3/ab,ea=[["second",s,[1,2,5,10,15,30]],["minute",y,[1,2,5,10,15,30]],["hour",C,[1,2,3,4,6,8,12]],["day",B,[1,2]],["week",I,[1,2]],["month",ga,[1,2,3,4,6]],["year",pb,null]],Ua=ea[6],ja=Ua[1],ba=Ua[2];for(k=0;k<ea.length;k++){Ua=ea[k];ja=Ua[1];ba=Ua[2];if(ea[k+1]){var ld=(ja*ba[ba.length-1]+ea[k+1][1])/2;if(Qa<=ld)break}}if(ja==pb&&Qa<5*ja)ba=[1,2,5];ea=na(Qa/ja,ba);var vb;ba=new Date(N*ab);ba.setMilliseconds(0);if(ja>=s)ba.setSeconds(ja>=y?0:ea*ib(ba.getSeconds()/
ea));if(ja>=y)ba[Pc](ja>=C?0:ea*ib(ba[qc]()/ea));if(ja>=C)ba[Qc](ja>=B?0:ea*ib(ba[rc]()/ea));if(ja>=B)ba[tc](ja>=ga?1:ea*ib(ba[Pb]()/ea));if(ja>=ga){ba[Rc](ja>=pb?0:ea*ib(ba[$b]()/ea));vb=ba[ac]()}if(ja>=pb){vb-=vb%ea;ba[Sc](vb)}ja==I&&ba[tc](ba[Pb]()-ba[sc]()+i.startOfWeek);k=1;vb=ba[ac]();s=ba.getTime()/ab;y=ba[$b]();for(C=ba[Pb]();s<Z&&k<xa;){fa.push(s);if(ja==pb)s=Zb(vb+k*ea,0)/ab;else if(ja==ga)s=Zb(vb,y+k*ea)/ab;else if(!q&&(ja==B||ja==I))s=Zb(vb,y,C+k*ea*(ja==B?1:7));else s+=ja*ea;k++}fa.push(s);
fc=i.dateTimeLabelFormats[Ua[0]]}function ka(k){var q=(ub<1?W(1/ub):1)*10;return W(k*q)/q}function Ha(){var k;k=ib(N/Qa)*Qa;var q=vc(Z/Qa)*Qa;fa=[];for(k=ka(k);k<=q;){fa.push(k);k=ka(k+Qa)}if(Pa){N-=0.5;Z+=0.5}}function ya(){jb?ua():Ha();var k=fa[0],q=fa[fa.length-1];if(i.startOnTick)N=k;else N>k&&fa.shift();if(i.endOnTick)Z=q;else Z<q&&fa.pop()}function za(){if(!jb&&!Pa){var k=Mb,q=fa.length;Mb=Nb[nb];if(q<Mb){for(;fa.length<Mb;)fa.push(ka(fa[fa.length-1]+Qa));hb*=(q-1)/(Mb-1)}if(T(k)&&Mb!=k)V.isDirty=
true}}function bb(){var k,q,s,y=N,C=Z;k=i.maxZoom;var B;r();N=z(Ca,i.min,H);Z=z(Qb,i.max,M);if(wc){B=m[L?"xAxis":"yAxis"][i.linkedTo];B=B.getExtremes();N=z(B.min,B.dataMin);Z=z(B.max,B.dataMax)}if(Z-N<k){B=(k-Z+N)/2;N=tb(N-B,z(i.min,N-B));Z=Lb(N+k,z(i.max,N+k))}if(!Pa&&!ec&&!wc&&T(N)&&T(Z)){k=Z-N||1;if(!T(i.min)&&!T(Ca)&&Vc&&(H<0||!Tc))N-=k*Vc;if(!T(i.max)&&!T(Qb)&&Wc&&(M>0||!Uc))Z+=k*Wc}Qa=Pa||N==Z?1:z(i.tickInterval,(Z-N)*i.tickPixelInterval/Oa);if(!jb&&!T(i.tickInterval))Qa=na(Qa);xc=i.minorTickInterval===
"auto"&&Qa?Qa/5:i.minorTickInterval;ya();hb=Oa/(Z-N||1);Nb||(Nb={x:0,y:0});if(!jb&&fa.length>Nb[nb])Nb[nb]=fa.length;if(!L)for(q in Za)for(s in Za[q])Za[q][s].cum=Za[q][s].total;if(!V.isDirty)V.isDirty=N!=y||Z!=C}function Ia(k,q,s){s=z(s,true);Aa(V,"setExtremes",{min:k,max:q},function(){if(Pa){if(k<0)k=0;if(q>Pa.length-1)q=Pa.length-1}Ca=k;Qb=q;s&&m.redraw()})}function Wa(){return{min:N,max:Z,dataMin:H,dataMax:M}}function qb(k){if(N>k)k=N;else if(Z<k)k=Z;return w(k,0,1)}function ca(k){var q=k.width,
s=q?yc:zc;s.push(k);q?J(k.value,k.color,k.width):K(k.from,k.to,k.color)}function u(){var k=i.title,q=i.alternateGridColor,s=i.minorTickWidth,y=i.lineWidth,C,B;C=U.length&&T(N)&&T(Z);if(p){p.empty();Q.empty()}else{p=P.g("axis").attr({zIndex:7}).add();Q=P.g("grid").attr({zIndex:1}).add()}if(C||wc){q&&o(fa,function(I,ga){if(ga%2===0&&I<Z)K(I,fa[ga+1]!==Ma?fa[ga+1]:Z,q)});o(zc,function(I){K(I.from,I.to,I.color)});if(xc&&!Pa)for(C=N;C<=Z;C+=xc){J(C,i.minorGridLineColor,i.minorGridLineWidth);s&&D(C,i.minorTickPosition,
i.minorTickColor,s,i.minorTickLength)}o(fa,function(I,ga){B=I+Db;J(B,i.gridLineColor,i.gridLineWidth);D(I,i.tickPosition,i.tickColor,i.tickWidth,i.tickLength,!(I==N&&!i.showFirstLabel||I==Z&&!i.showLastLabel),ga)});o(yc,function(I){J(I.value,I.color,I.width)})}if(!V.hasRenderedLine&&y){s=aa+(ia?xa:0)+Va;C=Ga-Cb-(ia?qa:0)+Va;P.path(P.crispLine([$a,Y?aa:s,Y?C:ha,Ja,Y?Ta-uc:s,Y?C:Ga-Cb],y)).attr({stroke:i.lineColor,"stroke-width":y,zIndex:7}).add();V.hasRenderedLine=true}if(!V.hasRenderedTitle&&!V.axisTitle&&
k&&k.text){y=Y?aa:ha;y={low:y+(Y?0:Oa),middle:y+Oa/2,high:y+(Y?Oa:0)}[k.align];s=(Y?ha+qa:aa)+(Y?1:-1)*(ia?-1:1)*k.margin-(Yb?parseInt(k.style.fontSize||12,10)/3:0);V.axisTitle=P.text(k.text,(Y?y:s+(ia?xa:0)+Va)+(k.x||0),(Y?s-(ia?qa:0)+Va:y)+(k.y||0),k.style,k.rotation||0,{low:"left",middle:"center",high:"right"}[k.align]).attr({zIndex:7}).add();V.hasRenderedTitle=true}V.isDirty=false}function v(k){o([zc,yc],function(q){for(var s=0;s<q.length;s++)if(q[s].id==k){q.splice(s,1);break}});u()}function E(){Ob.resetTracker&&
Ob.resetTracker();u();o(U,function(k){k.isDirty=true})}function S(k,q){V.categories=Pa=k;o(U,function(s){s.translate();s.setTooltipPoints(true)});V.isDirty=true;z(q,true)&&E()}var L=i.isX,ia=i.opposite,Y=oa?!L:L,Za={bar:{},column:{},area:{},areaspline:{},line:{}};i=ma(L?gc:Ac,Y?ia?md:Xc:ia?nd:od,i);var V=this,jb=i.type=="datetime",Va=i.offset||0,nb=L?"x":"y",Oa=Y?xa:qa,hb,Bb=Y?aa:Cb,p,Q,H,M,U,Ca,Qb,Z=null,N=null,Vc=i.minPadding,Wc=i.maxPadding,wc=T(i.linkedTo),Tc,Uc,ec,Yc=i.events,Bc,zc=i.plotBands||
[],yc=i.plotLines||[],Qa,xc,ub,fa,Mb,fc,kd=i.labels.formatter||function(){var k=this.value;return fc?hc(fc,k):k},Pa=i.categories||L&&m.columnCount,Ab=i.reversed,Db=Pa&&i.tickmarkPlacement=="between"?0.5:0;if(oa&&L&&Ab===Ma)Ab=true;ia||(Va*=-1);if(Y)Va*=-1;R(V,{addPlotBand:ca,addPlotLine:ca,adjustTickAmount:za,categories:Pa,getExtremes:Wa,getThreshold:qb,isXAxis:L,options:i,render:u,setExtremes:Ia,setScale:bb,setCategories:S,translate:w,redraw:E,removePlotBand:v,removePlotLine:v,reversed:Ab,stacks:Za});
for(Bc in Yc)kb(V,Bc,Yc[Bc]);bb()}function c(){function m(w,J,K,D){if(!r[w]){J=P.text(J,aa+xa-20,ha+30,a.toolbar.itemStyle,0,"right").on("click",D).attr({zIndex:20}).add();r[w]=J}}function i(w){bc(r[w].element);r[w]=null}var r={};return{add:m,remove:i}}function d(m){function i(ca,u){za=ka?ca:(2*za+ca)/3;bb=ka?u:(bb+u)/2;Ia.translate(za,bb);Cc=Ya(ca-za)>1||Ya(u-bb)>1?function(){i(ca,u)}:null}function r(){ka=true;Ia.hide()}function w(ca){var u=ca.series,v=m.borderColor||ca.color||u.color||"#606060",
E,S;S=ca.tooltipText;E=ca.tooltipPos;J=u;u=W(E?E[0]:oa?xa-ca.plotY:ca.plotX);ca=W(E?E[1]:oa?qa-ca.plotX:ca.plotY);E=Rb(u,ca);if(S===false||!E)r();else{if(ka){Ia.show();ka=false}qb.attr({text:S});S=qb.getBBox();Ha=S.width;ya=S.height;Wa.attr({width:Ha+2*na,height:ya+2*na,stroke:v});v=u-Ha+aa-25;u=ca-ya+ha+10;if(v<7){v=7;u-=20}if(u<5)u=5;else if(u+ya>Ga)u=Ga-ya-5;i(W(v-ua),W(u-ua))}}var J,K=m.borderWidth,D=m.style,na=parseInt(D.padding,10),ua=K+na,ka=true,Ha,ya,za=0,bb=0;D.padding=0;var Ia=P.g("tooltip").attr({zIndex:8}).add(),
Wa=P.rect(ua,ua,0,0,m.borderRadius,K).attr({fill:m.backgroundColor,"stroke-width":K}).add(Ia).shadow(m.shadow),qb=P.text("",na+ua,parseInt(D.fontSize,10)+na+ua).attr({zIndex:1}).css(D).add(Ia);return{refresh:w,hide:r}}function e(m,i){function r(u){u=u||lb.event;if(!u.target)u.target=u.srcElement;if(u.type!="mousemove"||lb.opera)Sb=id(Ba);if(u.layerX===Ma)if(Yb){u.layerX=u.x;u.layerY=u.y}else{u.layerX=u.pageX-Sb.x;u.layerY=u.pageY-Sb.y}return u}function w(u){var v={xAxis:[],yAxis:[]};o(Ra,function(E){var S=
E.translate,L=E.isXAxis,ia=oa?!L:L;v[L?"xAxis":"yAxis"].push({axis:E,value:S(ia?u.layerX-aa:qa-u.layerY+ha,true)})});return v}function J(u){var v=m.hoverPoint,E=m.hoverSeries;if(E&&E.tracker)(u=E.tooltipPoints[oa?u.layerY:u.layerX-aa])&&u!=v&&u.onMouseOver()}function K(){var u=m.hoverSeries,v=m.hoverPoint;v&&v.onMouseOut();u&&u.onMouseOut();Dc&&Dc.hide()}function D(){if(za){var u={xAxis:[],yAxis:[]},v=za.getBBox(),E=v.x-aa,S=v.y-ha;if(ya){o(Ra,function(L){var ia=L.translate,Y=L.isXAxis,Za=oa?!Y:Y,
V=ia(Za?E:qa-S-v.height,true);ia=ia(Za?E+v.width:qa-S,true);u[Y?"xAxis":"yAxis"].push({axis:L,min:Lb(V,ia),max:tb(V,ia)})});Aa(m,"selection",u,Ec)}za=za.destroy()}m.mouseIsDown=Fc=ya=false}function na(){var u=true;Ba.onmousedown=function(v){v=r(v);v.preventDefault&&v.preventDefault();m.mouseIsDown=Fc=true;ka=v.layerX;Ha=v.layerY;if(ic&&(Ia||Wa))za||(za=P.rect(aa,ha,qb?1:xa,ca?1:qa,0).attr({fill:"rgba(69,114,167,0.25)",zIndex:7}).add())};Ba.onmousemove=function(v){v=r(v);v.returnValue=false;var E=
v.layerX,S=v.layerY,L=!Rb(E-aa,S-ha);if(Fc){ya=Math.sqrt(Math.pow(ka-E,2)+Math.pow(Ha-S,2))>10;if(qb){v=E-ka;za.attr({width:Ya(v),x:(v>0?0:v)+ka})}if(ca){S=S-Ha;za.attr({height:Ya(S),y:(S>0?0:S)+Ha})}}else L||J(v);if(L&&!u){K();D()}u=L;return false};Ba.onmouseup=function(){D()};Ba.onclick=function(v){var E=m.hoverPoint;v=r(v);v.cancelBubble=true;if(!ya)if(E&&pa(v.target,"isTracker")){var S=E.plotX,L=E.plotY;R(E,{pageX:Sb.x+aa+(oa?xa-L:S),pageY:Sb.y+ha+(oa?qa-S:L)});Aa(m.hoverSeries,"click",R(v,{point:E}));
E.firePointEvent("click",v)}else{R(v,w(v));Rb(v.layerX-aa,v.layerY-ha)&&Aa(m,"click",v)}ya=false}}function ua(){m.trackerGroup=Gc=P.g("tracker");oa&&Gc.attr({width:m.plotWidth,height:m.plotHeight}).invert();Gc.attr({zIndex:9}).translate(aa,ha).add()}var ka,Ha,ya,za,bb=G.zoomType,Ia=/x/.test(bb),Wa=/y/.test(bb),qb=Ia&&!oa||Wa&&oa,ca=Wa&&!oa||Ia&&oa;ua();if(i.enabled)m.tooltip=Dc=d(i);na();Zc=setInterval(function(){Cc&&Cc()},32);R(this,{zoomX:Ia,zoomY:Wa,resetTracker:K})}function f(m){var i=m.type||
G.defaultSeriesType,r=cb[i],w=x.hasRendered;if(w)if(oa&&i=="column")r=cb.bar;else if(!oa&&i=="bar")r=cb.column;i=new r;i.init(x,m);if(!w&&i.inverted)oa=true;if(i.isCartesian)ic=i.isCartesian;ta.push(i);return i}function g(m,i){var r;i=z(i,true);Aa(x,"addSeries",{options:m},function(){r=f(m);r.isDirty=true;x.isDirty=true;i&&x.redraw()});return r}function j(){G.alignTicks!==false&&o(Ra,function(m){m.adjustTickAmount()})}function h(){for(var m=x.isDirty,i,r=ta.length,w=r,J;w--;){J=ta[w];if(J.isDirty&&
J.options.stacking){i=true;break}}if(i)for(w=r;w--;){J=ta[w];if(J.options.stacking)J.isDirty=true}o(ta,function(K){if(K.isDirty){K.cleanData();K.getSegments();if(K.options.legendType=="point")m=true}});Nb=null;if(ic){o(Ra,function(K){K.setScale()});j();o(Ra,function(K){K.isDirty&&K.redraw()})}o(ta,function(K){K.isDirty&&K.visible&&K.redraw()});if(m&&Hc.renderLegend){Hc.renderLegend();x.isDirty=false}Ob&&Ob.resetTracker&&Ob.resetTracker();Aa(x,"redraw")}function l(){var m=a.loading;if(!Eb){Eb=Fa(zb,
{className:"highcharts-loading"},R(m.style,{left:aa+Da,top:ha+Da,width:xa+Da,height:qa+Da,zIndex:10,display:fb}),Ba);Fa("span",{innerHTML:a.lang.loading},m.labelStyle,Eb)}if(!Ic){Na(Eb,{opacity:0,display:""});Tb(Eb,{opacity:m.style.opacity},{duration:m.showDuration});Ic=true}}function n(){Tb(Eb,{opacity:0},{duration:a.loading.hideDuration,complete:function(){Na(Eb,{display:fb})}});Ic=false}function t(m){var i,r,w;for(i=0;i<Ra.length;i++)if(Ra[i].options.id==m)return Ra[i];for(i=0;i<ta.length;i++)if(ta[i].options.id==
m)return ta[i];for(i=0;i<ta.length;i++){w=ta[i].data;for(r=0;r<w.length;r++)if(w[r].id==m)return w[r]}return null}function A(){var m=a.xAxis||{},i=a.yAxis||{},r;m=nc(m);o(m,function(w,J){w.index=J;w.isX=true});i=nc(i);o(i,function(w,J){w.index=J});Ra=m.concat(i);x.xAxis=[];x.yAxis=[];Ra=Fb(Ra,function(w){r=new b(x,w);x[r.isXAxis?"xAxis":"yAxis"].push(r);return r});j()}function F(){var m=[];o(ta,function(i){m=m.concat(jc(i.data,function(r){return r.selected}))});return m}function da(){return jc(ta,
function(m){return m.selected})}function X(){var m=a.title,i=m.align,r=a.subtitle,w=r.align,J={left:0,center:Ta/2,right:Ta};m&&m.text&&P.text(m.text,J[i]+m.x,m.y,m.style,0,i).attr({"class":"highcharts-title"}).add();r&&r.text&&P.text(r.text,J[w]+r.x,r.y,r.style,0,w).attr({"class":"highcharts-subtitle"}).add()}function O(){mb=G.renderTo;$c=Gb+Jc++;if(typeof mb=="string")mb=la.getElementById(mb);mb.innerHTML="";if(!mb.offsetWidth){wb=mb.cloneNode(0);Na(wb,{position:Ub,top:"-9999px",display:""});la.body.appendChild(wb)}var m=
(wb||mb).offsetHeight;x.chartWidth=Ta=G.width||(wb||mb).offsetWidth||600;x.chartHeight=Ga=G.height||(m>ha+Cb?m:0)||400;x.plotWidth=xa=Ta-aa-uc;x.plotHeight=qa=Ga-ha-Cb;x.plotLeft=aa;x.plotTop=ha;x.container=Ba=Fa(zb,{className:"highcharts-container"+(G.className?" "+G.className:""),id:$c},R({position:ad,overflow:xb,width:Ta+Da,height:Ga+Da,textAlign:"left"},G.style),wb||mb);x.renderer=P=G.renderer=="SVG"?new Vb(Ba,Ta,Ga):new bd(Ba,Ta,Ga)}function rb(){var m,i=a.labels,r=a.credits,w=G.borderWidth||
0,J=G.backgroundColor,K=G.plotBackgroundColor,D=G.plotBackgroundImage;m=2*w+(G.shadow?8:0);if(w||J)P.rect(m/2,m/2,Ta-m,Ga-m,G.borderRadius,w).attr({stroke:G.borderColor,"stroke-width":w,fill:J||fb}).add().shadow(G.shadow);K&&P.rect(aa,ha,xa,qa,0).attr({fill:K}).add().shadow(G.plotShadow);D&&P.image(D,aa,ha,xa,qa).add();G.plotBorderWidth&&P.rect(aa,ha,xa,qa,0,G.plotBorderWidth).attr({stroke:G.plotBorderColor,"stroke-width":G.plotBorderWidth,zIndex:4}).add();ic&&o(Ra,function(na){na.render()});X();
i.items&&o(i.items,function(){var na=R(i.style,this.style),ua=parseInt(na.left,10)+aa,ka=parseInt(na.top,10)+ha+12;delete na.left;delete na.top;P.text(this.html,ua,ka,na).attr({zIndex:2}).add()});o(ta,function(na){na.render()});Hc=x.legend=new pd(x);if(!x.toolbar)x.toolbar=c(x);r.enabled&&!x.credits&&P.text(r.text,Ta-10,Ga-5,r.style,0,"right").on("click",function(){location.href=r.href}).attr({zIndex:8}).add();x.hasRendered=true;if(wb){mb.appendChild(Ba);bc(wb)}}function db(){var m=ta.length;Hb(lb,
"unload",db);Hb(x);for(o(Ra,function(i){Hb(i)});m--;)ta[m].destroy();Ba.onmousedown=Ba.onmousemove=Ba.onmouseup=Ba.onclick=null;Ba.parentNode.removeChild(Ba);Ba=null;clearInterval(Zc);for(m in x)delete x[m]}function eb(){var m="onreadystatechange";if(Yb&&la.readyState!="complete")la.attachEvent(m,function(){la.detachEvent(m,arguments.callee);eb()});else{O();o(a.series||[],function(i){f(i)});x.inverted=oa=z(oa,a.chart.inverted);x.plotSizeX=qd=oa?qa:xa;x.plotSizeY=rd=oa?xa:qa;x.tracker=Ob=new e(x,a.tooltip);
A();o(ta,function(i){i.translate();i.setTooltipPoints()});x.render=rb;rb();Aa(x,"load")}}gc=ma(gc,wa.xAxis);Ac=ma(Ac,wa.yAxis);wa.xAxis=wa.yAxis=null;a=ma(wa,a);var G=a.chart,va=G.margin;va=typeof va=="number"?[va,va,va,va]:va;var ha=z(G.marginTop,va[0]),uc=z(G.marginRight,va[1]),Cb=z(G.marginBottom,va[2]),aa=z(G.marginLeft,va[3]),mb,wb,Ba,$c,Ta,Ga,x=this;va=G.events;var Kc,Lc,Rb,Dc,Fc,Eb,Ic,qa,xa,qd,rd,Ob,Gc,Hc,Sb,ic=G.showAxes,Ra=[],Nb,ta=[],oa,P,Cc,Zc,Ec,cd,pd=function(m){function i(p,Q){var H=
p.legendItem,M=p.legendLine,U=p.legendSymbol,Ca=Ia.color,Qb=Q?D.itemStyle.color:Ca;p=Q?p.color:Ca;H&&H.css({color:Qb});M&&M.attr({stroke:p});U&&U.attr({stroke:p,fill:p})}function r(p,Q,H){var M=p.legendItem,U=p.legendLine,Ca=p.legendSymbol;p=p.checkbox;M&&M.attr({x:Q,y:H});U&&U.translate(Q,H-4);Ca&&Ca.translate(Q,H);if(p){p.x=Q;p.y=H}}function w(p){for(var Q=Ha.length,H=p.checkbox;Q--;)if(Ha[Q]==p){Ha.splice(Q,1);break}o(["legendItem","legendLine","legendSymbol"],function(M){p[M]&&p[M].destroy()});
H&&bc(p.checkbox)}function J(p){var Q,H,M=p.legendItem;H=p.series||p;if(!M){H=/^(bar|pie|area|column)$/.test(H.type);p.legendItem=M=P.text(D.labelFormatter.call(p),0,0).css(p.visible?za:Ia).on("mouseover",function(){p.setState(ob);M.css(bb)}).on("mouseout",function(){M.css(p.visible?za:Ia);p.setState()}).on("click",function(){var U="legendItemClick",Ca=function(){p.setVisible()};p.firePointEvent?p.firePointEvent(U,null,Ca):Aa(p,U,null,Ca)}).attr({zIndex:2}).add(V);if(!H&&p.options&&p.options.lineWidth)p.legendLine=
P.path([$a,-ua-ka,0,Ja,-ka,0]).attr({"stroke-width":p.options.lineWidth,zIndex:2}).add(V);if(H)Q=P.rect(-ua-ka,-11,ua,12,2).attr({"stroke-width":0,zIndex:3}).add(V);else if(p.options&&p.options.marker&&p.options.marker.enabled)Q=P.symbol(p.symbol,-ua/2-ka,-4,p.options.marker.radius).attr(p.pointAttr[La]).attr({zIndex:3}).add(V);p.legendSymbol=Q;i(p,p.visible);if(p.options&&p.options.showCheckbox){p.checkbox=Fa("input",{type:"checkbox",checked:p.selected,defaultChecked:p.selected},D.itemCheckboxStyle,
Ba);kb(p.checkbox,"click",function(U){U=U.target;Aa(p,"checkboxClick",{checked:U.checked},function(){p.select()})})}}r(p,E,S);Q=M.getBBox();L=S;p.legendItemWidth=Q=D.itemWidth||ua+ka+Q.width+qb;if(na){E+=Q;jb=Va||tb(E-v,jb);if(E-v+Q>(Va||Ta-2*Wa-v)){E=v;S+=ca}}else{S+=ca;jb=Va||tb(Q,jb)}Ha.push(p)}function K(){E=v;S=u;L=jb=0;V||(V=P.g("legend").attr({zIndex:7}).add());Bb&&hb.reverse();o(hb,function(U){if(U.options.showInLegend){U=U.options.legendType=="point"?U.data:[U];o(U,J)}});Bb&&hb.reverse();
nb=Va||jb;Oa=L-u+ca;if(Y||Za){nb+=2*Wa;Oa+=2*Wa;if(ia)ia.attr({height:Oa,width:nb});else ia=P.rect(0,0,nb,Oa,D.borderRadius,Y||0).attr({stroke:D.borderColor,"stroke-width":Y||0,fill:Za||fb}).add(V).shadow(D.shadow)}for(var p=["left","right","top","bottom"],Q,H=4;H--;){Q=p[H];if(ya[Q]&&ya[Q]!="auto"){D[H<2?"align":"verticalAlign"]=Q;D[H<2?"x":"y"]=parseInt(ya[Q],10)*(H%2?-1:1)}}var M=Lc(R({width:nb,height:Oa},D));V.translate(M.x,M.y);o(Ha,function(U){var Ca=U.checkbox;Ca&&Na(Ca,{left:M.x+U.legendItemWidth+
Ca.x-40+Da,top:M.y+Ca.y-11+Da})})}var D=m.options.legend;if(D.enabled){var na=D.layout=="horizontal",ua=D.symbolWidth,ka=D.symbolPadding,Ha=[],ya=D.style,za=D.itemStyle,bb=D.itemHoverStyle,Ia=D.itemHiddenStyle,Wa=parseInt(ya.padding,10),qb=20,ca=D.lineHeight||16,u=18,v=4+Wa+ua+ka,E,S,L,ia,Y=D.borderWidth,Za=D.backgroundColor,V,jb,Va=D.width,nb,Oa,hb=m.series,Bb=D.reversed;K();return{colorizeItem:i,destroyItem:w,renderLegend:K}}};Rb=function(m,i){var r=0,w=0;return m>=r&&m<=r+xa&&i>=w&&i<=w+qa};cd=
function(){Aa(x,"selection",{resetSelection:true},Ec);x.toolbar.remove("zoom")};Ec=function(m){var i=wa.lang;x.toolbar.add("zoom",i.resetZoom,i.resetZoomTitle,cd);!m||m.resetSelection?o(Ra,function(r){r.setExtremes(null,null,false)}):o(m.xAxis.concat(m.yAxis),function(r){var w=r.axis;if(x.tracker[w.isXAxis?"zoomX":"zoomY"])w.setExtremes(r.min,r.max,false)});h()};Lc=function(m){var i=m.align,r=m.verticalAlign,w=m.x||0,J=m.y||0,K={x:w||0,y:J||0};if(/^(right|center)$/.test(i))K.x=(Ta-m.width)/{right:1,
center:2}[i]+w;if(/^(bottom|middle)$/.test(r))K.y=(Ga-m.height)/{bottom:1,middle:2}[r]+J;return K};kc=sb=0;kb(lb,"unload",db);if(va)for(Kc in va)kb(x,Kc,va[Kc]);x.options=a;x.series=ta;x.addSeries=g;x.destroy=db;x.get=t;x.getAlignment=Lc;x.getSelectedPoints=F;x.getSelectedSeries=da;x.hideLoading=n;x.isInsidePlot=Rb;x.redraw=h;x.showLoading=l;eb()}function dd(a){var b=[],c=[],d;for(d=0;d<a.length;d++){b[d]=a[d].plotX;c[d]=a[d].plotY}this.xdata=b;this.ydata=c;a=[];this.y2=[];var e=c.length;this.n=e;
this.y2[0]=0;this.y2[e-1]=0;a[0]=0;for(d=1;d<e-1;d++){var f=b[d+1]-b[d-1];f=(b[d]-b[d-1])/f;var g=f*this.y2[d-1]+2;this.y2[d]=(f-1)/g;a[d]=(c[d+1]-c[d])/(b[d+1]-b[d])-(c[d]-c[d-1])/(b[d]-b[d-1]);a[d]=(6*a[d]/(b[d+1]-b[d-1])-f*a[d-1])/g}for(b=e-2;b>=0;b--)this.y2[b]=this.y2[b]*this.y2[b+1]+a[b]}var la=document,lb=window,Ka=Math,W=Ka.round,ib=Ka.floor,vc=Ka.ceil,tb=Ka.max,Lb=Ka.min,Ya=Ka.abs,Ib=Ka.cos,Jb=Ka.sin,ra=navigator.userAgent,Yb=/msie/i.test(ra)&&!lb.opera,sd=/AppleWebKit/.test(ra),Mc=lb.SVGAngle||
la.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1"),sb,kc,td={},Jc=0,ab=1,cc,wa,hc,Ma,zb="div",Ub="absolute",ad="relative",xb="hidden",Gb="highcharts-",Wb="visible",Da="px",fb="none",$a="M",Ja="L",ed="rgba(192,192,192,"+(Mc?1.0E-6:0.0020)+")",La="",ob="hover",yb="select",Zb,qc,rc,sc,Pb,$b,ac,Pc,Qc,tc,Rc,Sc,Ea=lb.HighchartsAdapter,sa=Ea||{},o=sa.each,jc=sa.grep,Fb=sa.map,ma=sa.merge,pc=sa.hyphenate,kb=sa.addEvent,Hb=sa.removeEvent,Aa=sa.fireEvent,Tb=sa.animate,lc=
sa.stop;sa=sa.getAjax;var cb={};if(!Ea&&lb.jQuery){var Xa=jQuery;o=function(a,b){for(var c=0,d=a.length;c<d;c++)if(b.call(a[c],a[c],c,a)===false)return c};jc=Xa.grep;Fb=function(a,b){for(var c=[],d=0,e=a.length;d<e;d++)c[d]=b.call(a[d],a[d],d,a);return c};ma=function(){var a=arguments;return Xa.extend(true,null,a[0],a[1],a[2],a[3])};pc=function(a){return a.replace(/([A-Z])/g,function(b,c){return"-"+c.toLowerCase()})};kb=function(a,b,c){Xa(a).bind(b,c)};Hb=function(a,b,c){var d=la.removeEventListener?
"removeEventListener":"detachEvent";if(la[d]&&!a[d])a[d]=function(){};Xa(a).unbind(b,c)};Aa=function(a,b,c,d){var e=Xa.Event(b),f="detached"+b;R(e,c);if(a[b]){a[f]=a[b];a[b]=null}Xa(a).trigger(e);if(a[f]){a[b]=a[f];a[f]=null}d&&!e.isDefaultPrevented()&&d(e)};Tb=function(a,b,c){a=Xa(a);a.stop();a.animate(b,c)};lc=function(a){Xa(a).stop()};sa=function(a,b){Xa.get(a,null,b)};Xa.extend(Xa.easing,{easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c}});var ud=jQuery.fx.step._default,vd=jQuery.fx.prototype.cur;
Xa.fx.step._default=function(a){var b=a.elem;b.attr?b.attr(a.prop,a.now):ud.apply(this,arguments)};Xa.fx.prototype.cur=function(){var a=this.elem;return a=a.attr?a.attr(this.prop):vd.apply(this,arguments)}}else if(!Ea&&lb.MooTools){o=$each;Fb=function(a,b){return a.map(b)};jc=function(a,b){return a.filter(b)};ma=$merge;pc=function(a){return a.hyphenate()};kb=function(a,b,c){if(typeof b=="string"){if(b=="unload")b="beforeunload";if(!a.addEvent)if(a.nodeName)a=$(a);else R(a,new Events);a.addEvent(b,
c)}};Hb=function(a,b,c){if(b){if(b=="unload")b="beforeunload";a.removeEvent(b,c)}};Aa=function(a,b,c,d){b=new Event({type:b,target:a});b=R(b,c);b.preventDefault=function(){d=null};a.fireEvent&&a.fireEvent(b.type,b);d&&d(b)};Tb=function(a,b,c){var d=a.attr;if(d&&!a.setStyle){a.setStyle=a.getStyle=a.attr;a.$family=a.uid=true}lc(a);c=new Fx.Morph(d?a:$(a),R(c,{transition:Fx.Transitions.Quad.easeInOut}));c.start(b);a.fx=c};lc=function(a){a.fx&&a.fx.cancel()};sa=function(a,b){(new Request({url:a,method:"get",
onSuccess:b})).send()}}Ea={enabled:true,align:"center",x:0,y:15,style:{color:"#666",fontSize:"11px"}};wa={colors:["#4572A7","#AA4643","#89A54E","#80699B","#3D96AE","#DB843D","#92A8CD","#A47D7C","#B5CA92"],symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:["January","February","March","April","May","June","July","August","September","October","November","December"],weekdays:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],decimalPoint:".",
resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:true},chart:{margin:[50,50,90,80],borderColor:"#4572A7",borderRadius:5,defaultSeriesType:"line",ignoreHiddenSeries:true,style:{fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Verdana, Arial, Helvetica, sans-serif',fontSize:"12px"},backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0"},title:{text:"Chart title",x:0,y:20,align:"center",style:{color:"#3E576F",fontSize:"16px"}},subtitle:{text:"",x:0,y:40,align:"center",
style:{color:"#6D869F"}},plotOptions:{line:{allowPointSelect:false,showCheckbox:false,animation:true,events:{},lineWidth:2,shadow:true,marker:{enabled:true,lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:ma(Ea,{enabled:false,y:-6,formatter:function(){return this.y}}),showInLegend:true,states:{hover:{lineWidth:3,marker:{}},select:{marker:{}}},stickyTracking:true}},labels:{style:{position:Ub,color:"#3E576F"}},
legend:{enabled:true,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderWidth:1,borderColor:"#909090",borderRadius:5,shadow:false,style:{padding:"5px"},itemStyle:{cursor:"pointer",color:"#3E576F"},itemHoverStyle:{color:"#000000"},itemHiddenStyle:{color:"#C0C0C0"},itemCheckboxStyle:{position:Ub,width:"13px",height:"13px"},symbolWidth:16,symbolPadding:5,verticalAlign:"bottom",x:15,y:-15},loading:{hideDuration:100,labelStyle:{fontWeight:"bold",position:ad,top:"1em"},
showDuration:100,style:{position:Ub,backgroundColor:"white",opacity:0.5,textAlign:"center"}},tooltip:{enabled:true,formatter:function(){var a=this,b=a.series,c=b.xAxis,d=a.x;return"<b>"+(a.point.name||b.name)+"</b><br/>"+(T(d)?"X value: "+(c&&c.options.type=="datetime"?hc(null,d):d)+"<br/>":"")+"Y value: "+a.y},backgroundColor:"rgba(255, 255, 255, .85)",borderWidth:2,borderRadius:5,shadow:true,snap:10,style:{color:"#333333",fontSize:"12px",padding:"5px",whiteSpace:"nowrap"}},toolbar:{itemStyle:{color:"#4572A7",
cursor:"pointer"}},credits:{enabled:true,text:"Highcharts.com",href:"http://www.highcharts.com",style:{cursor:"pointer",color:"#909090",fontSize:"10px"}}};var gc={dateTimeLabelFormats:{second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:false,gridLineColor:"#C0C0C0",labels:Ea,lineColor:"#C0D0E0",lineWidth:1,max:null,min:null,minPadding:0.01,maxPadding:0.01,maxZoom:null,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",
minorTickLength:2,minorTickPosition:"outside",minorTickWidth:1,showFirstLabel:true,showLastLabel:false,startOfWeek:1,startOnTick:false,tickColor:"#C0D0E0",tickLength:5,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",margin:35,style:{color:"#6D869F",fontWeight:"bold"}},type:"linear"},Ac=ma(gc,{endOnTick:true,gridLineWidth:1,tickPixelInterval:72,showLastLabel:true,labels:{align:"right",x:-8,y:3},lineWidth:0,maxPadding:0.05,minPadding:0.05,startOnTick:true,
tickWidth:0,title:{margin:40,rotation:270,text:"Y-values"}}),od={labels:{align:"right",x:-8,y:3},title:{rotation:270}},nd={labels:{align:"left",x:8,y:3},title:{rotation:90}},Xc={labels:{align:"center",x:0,y:14},title:{rotation:0}},md=ma(Xc,{labels:{y:-5}});Ea=wa.plotOptions;sa=Ea.line;Ea.spline=ma(sa);Ea.scatter=ma(sa,{lineWidth:0,states:{hover:{lineWidth:0}}});Ea.area=ma(sa,{});Ea.areaspline=ma(Ea.area);Ea.column=ma(sa,{borderColor:"#FFFFFF",borderWidth:1,borderRadius:0,groupPadding:0.2,marker:null,
pointPadding:0.1,minPointLength:0,states:{hover:{brightness:0.1,shadow:false},select:{color:"#C0C0C0",borderColor:"#000000",shadow:false}}});Ea.bar=ma(Ea.column,{dataLabels:{align:"left",x:5,y:0}});Ea.pie=ma(sa,{borderColor:"#FFFFFF",borderWidth:1,center:["50%","50%"],colorByPoint:true,legendType:"point",marker:null,size:"90%",slicedOffset:10,states:{hover:{brightness:0.1,shadow:false}}});Oc();var Kb=function(a){function b(j){if(g=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/.exec(j))f=
[parseInt(g[1],10),parseInt(g[2],10),parseInt(g[3],10),parseFloat(g[4],10)];else if(g=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(j))f=[parseInt(g[1],16),parseInt(g[2],16),parseInt(g[3],16),1]}function c(j){return j=f&&!isNaN(f[0])?j=="rgb"?"rgb("+f[0]+","+f[1]+","+f[2]+")":j=="a"?f[3]:"rgba("+f.join(",")+")":a}function d(j){if(typeof j=="number"&&j!==0)for(var h=0;h<3;h++){f[h]+=parseInt(j*255,10);if(f[h]<0)f[h]=0;if(f[h]>255)f[h]=255}return this}function e(j){f[3]=j;return this}var f=
[],g;b(a);return{get:c,brighten:d,setOpacity:e}};hc=function(a,b,c){function d(A){return A.toString().replace(/^([0-9])$/,"0$1")}if(!T(b)||isNaN(b))return"Invalid date";a=z(a,"%Y-%m-%d %H:%M:%S");b=new Date(b*ab);var e=b[rc](),f=b[sc](),g=b[Pb](),j=b[$b](),h=b[ac](),l=wa.lang,n=l.weekdays;l=l.months;b={a:n[f].substr(0,3),A:n[f],d:d(g),e:g,b:l[j].substr(0,3),B:l[j],m:d(j+1),y:h.toString().substr(2,2),Y:h,H:d(e),I:d(e%12||12),l:e%12||12,M:d(b[qc]()),p:e<12?"AM":"PM",P:e<12?"am":"pm",S:d(b.getSeconds())};
for(var t in b)a=a.replace("%"+t,b[t]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};dc.prototype={init:function(a,b){this.element=la.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b){Tb(this,a,b)},attr:function(a,b){var c,d,e,f=this.element,g=f.nodeName,j=this.renderer,h,l=this.shadows,n,t=this;if(typeof a=="string"&&T(b)){c=a;a={};a[c]=b}if(typeof a=="string"){c=a;if(g=="circle")c={x:"cx",y:"cy"}[c]||c;else if(c=="strokeWidth")c="stroke-width";t=parseFloat(pa(f,
c)||this[c]||0)}else for(c in a){b=a[c];if(c=="d"){if(typeof b!="string")b=b.join(" ");if(/(NaN|  )/.test(b))b="M 0 0"}else if(c=="x"&&g=="text")for(d=0;d<f.childNodes.length;d++){e=f.childNodes[d];pa(e,"x")==pa(f,"x")&&pa(e,"x",b)}else if(c=="fill")b=j.color(b,f,c);else if(g=="circle")c={x:"cx",y:"cy"}[c]||c;else if(c=="translateX"||c=="translateY"){this[c]=b;this.updateTransform();h=true}else if(c=="stroke")b=j.color(b,f,c);else if(c=="isTracker")this[c]=b;if(c=="strokeWidth")c="stroke-width";if(sd&&
c=="stroke-width"&&b===0)b=1.0E-6;if(this.symbolName&&/^(x|y|r|start|end|innerR)/.test(c)){if(!n){this.symbolAttr(a);n=true}h=true}if(l&&/^(width|height|visibility|x|y|d)$/.test(c))for(d=l.length;d--;)pa(l[d],c,b);if(c=="text")j.buildText(f,b);else h||pa(f,c,b)}return t},symbolAttr:function(a){var b=this;b.x=z(a.x,b.x);b.y=parseFloat(z(a.y,b.y));b.r=z(a.r,b.r);b.start=z(a.start,b.start);b.end=z(a.end,b.end);b.width=z(a.width,b.width);b.height=parseFloat(z(a.height,b.height));b.innerR=z(a.innerR,b.innerR);
b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.r,{start:b.start,end:b.end,width:b.width,height:b.height,innerR:b.innerR})})},clip:function(a){return this.attr("clip-path","url("+this.renderer.url+"#"+a.id+")")},css:function(a){var b=this;if(a&&a.color)a.fill=a.color;a=R(b.styles,a);b.attr({style:oc(a)});b.styles=a;return b},on:function(a,b){this.element["on"+a]=b;return this},translate:function(a,b){var c=this;c.translateX=a;c.translateY=b;c.updateTransform();return c},invert:function(){var a=
this;a.inverted=true;a.updateTransform();return a},updateTransform:function(){var a=this,b=a.translateX||0,c=a.translateY||0,d=a.inverted,e=[];if(d){b+=a.attr("width");c+=a.attr("height")}if(b||c)e.push("translate("+b+","+c+")");d&&e.push("rotate(90) scale(-1,1)");e.length&&pa(a.element,"transform",e.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},getBBox:function(){return this.element.getBBox()},show:function(){return this.attr({visibility:Wb})},hide:function(){return this.attr({visibility:xb})},
add:function(a){var b=this.renderer,c=a||b;b=c.element||b.box;var d=b.childNodes,e=this.element,f=pa(e,"zIndex"),g;this.parentInverted=a&&a.inverted;if(f)c.handleZ=true;if(c.handleZ)for(g=0;g<d.length;g++){a=d[g];c=pa(a,"zIndex");if(a!=e&&(c>f||!T(f)&&T(c))){b.insertBefore(e,a);return this}}b.appendChild(e);return this},destroy:function(){var a=this,b=a.element,c=a.shadows,d=b.parentNode,e;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=null;lc(a);d&&d.removeChild(b);c&&o(c,function(f){(d=f.parentNode)&&
d.removeChild(f)});for(e in a)delete a[e];return null},empty:function(){for(var a=this.element,b=a.childNodes,c=b.length;c--;)a.removeChild(b[c])},shadow:function(a){var b=[],c,d=this.element,e=this.parentInverted?"(-1,-1)":"(1,1)";if(a){for(a=1;a<=3;a++){c=d.cloneNode(0);pa(c,{isShadow:"true",stroke:"rgb(0, 0, 0)","stroke-opacity":0.05*a,"stroke-width":7-2*a,transform:"translate"+e,fill:fb});d.parentNode.insertBefore(c,d);b.push(c)}this.shadows=b}return this}};var Vb=function(){this.init.apply(this,
arguments)};Vb.prototype={init:function(a,b,c){var d=la.createElementNS("http://www.w3.org/2000/svg","svg"),e=location;pa(d,{width:b,height:c,xmlns:"http://www.w3.org/2000/svg",version:"1.1"});a.appendChild(d);this.Element=dc;this.box=d;this.url=e.href.replace(/#.*?$/,"");this.defs=this.createElement("defs").add()},createElement:function(a){var b=new this.Element;b.init(this,a);return b},buildText:function(a,b){b=b.toString().replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,
'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,"</span>").split(/<br[^>]?>/g);var c=a.childNodes,d=/style="([^"]+)"/,e=/href="([^"]+)"/,f=pa(a,"x"),g;for(g=c.length-1;g>=0;g--)a.removeChild(c[g]);o(b,function(j,h){var l,n=0;j=j.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");l=j.split("|||");o(l,function(t){if(t!==""||l.length==1){var A={},F=la.createElementNS("http://www.w3.org/2000/svg","tspan");d.test(t)&&pa(F,"style",t.match(d)[1].replace(/(;| |^)color([ :])/,
"$1fill$2"));if(e.test(t)){pa(F,"onclick",'location.href="'+t.match(e)[1]+'"');Na(F,{cursor:"pointer"})}t=t.replace(/<(.|\n)*?>/g,"");F.appendChild(la.createTextNode(t));if(n)A.dx=3;else A.x=f;if(h&&!n)A.dy=16;pa(F,A);a.appendChild(F);n++}})})},crispLine:function(a,b){if(a[1]==a[4])a[1]=a[4]=W(a[1])+b%2/2;if(a[2]==a[5])a[2]=a[5]=W(a[2])+b%2/2;return a},path:function(a){return this.createElement("path").attr({d:a,fill:fb})},circle:function(a,b,c){a=typeof a=="object"?a:{x:a,y:b,r:c};return this.createElement("circle").attr(a)},
arc:function(a,b,c,d,e,f){if(typeof a=="object"){b=a.y;c=a.r;d=a.innerR;e=a.start;f=a.end;a=a.x}return this.symbol("arc",a||0,b||0,c||0,{innerR:d||0,start:e||0,end:f||0})},rect:function(a,b,c,d,e,f){if(arguments.length>1){var g=(f||0)%2/2;a=W(a||0)+g;b=W(b||0)+g;c=W((c||0)-2*g);d=W((d||0)-2*g)}g=typeof a=="object"?a:{x:a,y:b,width:tb(c,0),height:tb(d,0)};return this.createElement("rect").attr(R(g,{rx:e||g.r,ry:e||g.r,fill:fb}))},g:function(a){return this.createElement("g").attr(T(a)&&{"class":Gb+
a})},image:function(a,b,c,d,e){b=this.createElement("image").attr({x:b,y:c,width:d,height:e,preserveAspectRatio:fb});b.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a);return b},symbol:function(a,b,c,d,e){var f,g=this.symbols[a];g=g&&g(b,c,d,e);var j=/^url\((.*?)\)$/;if(g){f=this.path(g);R(f,{symbolName:a,x:b,y:c,r:d});e&&R(f,e)}else if(j.test(a)){a=a.match(j)[1];f=this.image(a).attr({visibility:xb});Fa("img",{onload:function(){var h=this;h=td[h.src]||[h.width,h.height];f.attr({x:W(b-
h[0]/2)+Da,y:W(c-h[1]/2)+Da,width:h[0],height:h[1],visibility:"inherit"})},src:a})}else f=this.circle(b,c,d);return f},symbols:{square:function(a,b,c){c=0.707*c;return[$a,a-c,b-c,Ja,a+c,b-c,a+c,b+c,a-c,b+c,"Z"]},triangle:function(a,b,c){return[$a,a,b-1.33*c,Ja,a+c,b+0.67*c,a-c,b+0.67*c,"Z"]},"triangle-down":function(a,b,c){return[$a,a,b+1.33*c,Ja,a-c,b-0.67*c,a+c,b-0.67*c,"Z"]},diamond:function(a,b,c){return[$a,a,b-c,Ja,a+c,b,a,b+c,a-c,b,"Z"]},arc:function(a,b,c,d){var e=Math.PI,f=d.start,g=d.end-
1.0E-6,j=d.innerR,h=Ib(f),l=Jb(f),n=Ib(g);g=Jb(g);d=d.end-f<e?0:1;return[$a,a+c*h,b+c*l,"A",c,c,0,d,1,a+c*n,b+c*g,Ja,a+j*n,b+j*g,"A",j,j,0,d,0,a+j*h,b+j*l,"Z"]}},clipRect:function(a,b,c,d){var e=Gb+Jc++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=this.rect(a,b,c,d,0).add(f);a.id=e;return a},color:function(a,b,c){var d,e=/^rgba/;if(a&&a.linearGradient){var f=this;b="linearGradient";c=a[b];var g=Gb+Jc++,j,h,l;j=f.createElement(b).attr({id:g,gradientUnits:"userSpaceOnUse",x1:c[0],
y1:c[1],x2:c[2],y2:c[3]}).add(f.defs);o(a.stops,function(n){if(e.test(n[1])){d=Kb(n[1]);h=d.get("rgb");l=d.get("a")}else{h=n[1];l=1}f.createElement("stop").attr({offset:n[0],"stop-color":h,"stop-opacity":l}).add(j)});return"url("+this.url+"#"+g+")"}else if(e.test(a)){d=Kb(a);pa(b,c+"-opacity",d.get("a"));return d.get("rgb")}else return a},text:function(a,b,c,d,e,f){d=d||{};f=f||"left";e=e||0;var g=d.color||"#000000",j=wa.chart.style;b=W(z(b,0));c=W(z(c,0));R(d,{fontFamily:d.fontFamily||j.fontFamily,
fontSize:d.fontSize||j.fontSize});d=oc(d);a={x:b,y:c,text:a,fill:g,style:d.replace(/"/g,"'")};if(e||f!="left")a=R(a,{"text-anchor":{left:"start",center:"middle",right:"end"}[f],transform:"rotate("+e+" "+b+" "+c+")"});return this.createElement("text").attr(a)}};var Nc;if(!Mc){var wd=gb(dc,{init:function(a,b){var c=["<",b,' filled="f" stroked="f"'],d=["position: ",Ub,";"];if(b=="shape"||b==zb)d.push("left:0;top:0;width:10px;height:10px");c.push(' style="',d.join(""),'"/>');if(b){c=b==zb||b=="span"||
b=="img"?c.join(""):a.prepVML(c);this.element=Fa(c)}this.renderer=a},add:function(a){var b=this,c=b.renderer,d=b.element,e=c.box;c=a&&a.inverted;a=a?a.element||a:e;if(c){c=a.style;Na(d,{flip:"x",left:parseInt(c.width,10)-10,top:parseInt(c.height,10)-10,rotation:-90})}a.appendChild(d);return b},attr:function(a,b){var c,d,e,f=this.element,g=f.style,j=f.nodeName,h=this.renderer,l=this.symbolName,n,t=this.shadows,A=la.documentMode,F,da=this;if(typeof a=="string"&&T(b)){c=a;a={};a[c]=b}if(typeof a=="string"){c=
a;da=c=="strokeWidth"||c=="stroke-width"?f.strokeweight:z(this[c],parseInt(g[{x:"left",y:"top"}[c]||c],10))}else for(c in a){d=a[c];F=false;if(l&&/^(x|y|r|start|end|width|height|innerR)/.test(c)){if(!n){this.symbolAttr(a);n=true}F=true}else if(c=="d"){e=d.length;for(F=[];e--;)F[e]=typeof d[e]=="number"?W(d[e]*10)-5:d[e]=="Z"?"x":d[e];d=F.join(" ")||"x";f.path=d;if(t)for(e=t.length;e--;)t[e].path=d;F=true}else if(c=="zIndex"||c=="visibility"){g[c]=d;A==8&&c=="visibility"&&j=="DIV"&&o(f.childNodes,
function(X){Na(X,{visibility:d})});F=true}else if(/^(width|height)$/.test(c)){g[c]=d;this.updateClipping&&this.updateClipping();F=true}else if(/^(x|y)$/.test(c)){if(c=="y"&&f.tagName=="SPAN"&&f.lineHeight)d-=f.lineHeight;g[{x:"left",y:"top"}[c]]=d}else if(c=="class")f.className=d;else if(c=="stroke"){d=h.color(d,f,c);c="strokecolor"}else if(c=="stroke-width"||c=="strokeWidth"){f.stroked=d?true:false;c="strokeweight";if(typeof d=="number")d+=Da}else if(c=="fill")if(j=="SPAN")g.color=d;else{f.filled=
d!=fb?true:false;d=h.color(d,f,c);c="fillcolor"}else if(c=="translateX"||c=="translateY"){this[c]=b;this.updateTransform();F=true}if(t&&c=="visibility")for(e=t.length;e--;)t[e].style[c]=d;if(c=="text")f.innerHTML=d;else if(!F)if(A==8)f[c]=d;else pa(f,c,d)}return da},clip:function(a){var b=this,c=a.members,d=c.length;c.push(b);b.destroyClip=function(){c.splice(d,1)};return b.css(a.getCSS(b.inverted))},css:function(a){var b=this;Na(b.element,a);return b},destroy:function(){var a=this;a.destroyClip&&
a.destroyClip();dc.prototype.destroy.apply(this)},empty:function(){var a=this.element;a=a.childNodes;for(var b=a.length,c;b--;){c=a[b];c.parentNode.removeChild(c)}},getBBox:function(){var a=this.element,b,c=a.offsetWidth,d=a.parentNode;c||la.body.appendChild(a);b={x:a.offsetLeft,y:a.offsetTop,width:a.offsetWidth,height:a.offsetHeight};c||(d?d.appendChild(a):la.body.removeChild(a));return b},on:function(a,b){this.element["on"+a]=function(){var c=lb.event;c.target=c.srcElement;b(c)};return this},updateTransform:function(){var a=
this,b=a.translateX||0,c=a.translateY||0;if(b||c)a.css({left:b,top:c})},shadow:function(a){var b=[],c=this.element,d=this.renderer,e,f=c.style,g,j=c.path;if(""+c.path=="")j="x";if(a){for(a=1;a<=3;a++){g=['<shape isShadow="true" strokeweight="',7-2*a,'" filled="false" path="',j,'" coordsize="100,100" style="',c.style.cssText,'" />'];e=Fa(d.prepVML(g),null,{left:parseInt(f.left,10)+1,top:parseInt(f.top,10)+1});g=['<stroke color="black" opacity="',0.05*a,'"/>'];Fa(d.prepVML(g),null,null,e);c.parentNode.insertBefore(e,
c);b.push(e)}this.shadows=b}return this}});Nc=function(){this.init.apply(this,arguments)};Nc.prototype=ma(Vb.prototype,{isIE8:ra.indexOf("MSIE 8.0")>-1,init:function(a,b,c){this.width=b;this.height=c;this.box=Fa(zb,null,{width:b+Da,height:c+Da},a);this.Element=wd;if(!la.namespaces.hcv){la.namespaces.add("hcv","urn:schemas-microsoft-com:vml");la.createStyleSheet().cssText="hcv\\:fill, hcv\\:path, hcv\\:textpath, hcv\\:shape, hcv\\:stroke, hcv\\:line { behavior:url(#default#VML); display: inline-block; } "}},
clipRect:function(a,b,c,d){var e=this.createElement();return R(e,{members:[],element:{style:{left:a,top:b,width:c,height:d}},getCSS:function(f){var g=e.element.style,j=g.top,h=g.left,l=h+g.width;g=j+g.height;j={clip:"rect("+(f?h:j)+"px,"+(f?g:l)+"px,"+(f?l:g)+"px,"+(f?j:h)+"px)"};!f&&la.documentMode==8&&R(j,{width:l+Da,height:g+Da});return j},updateClipping:function(){o(e.members,function(f){f.css(e.getCSS(f.inverted))})}})},color:function(a,b,c){var d,e=/^rgba/;if(a&&a.linearGradient){var f,g,j=
a.linearGradient,h,l,n,t;o(a.stops,function(A,F){if(e.test(A[1])){d=Kb(A[1]);f=d.get("rgb");g=d.get("a")}else{f=A[1];g=1}if(F){n=f;t=g}else{h=f;l=g}});a=90-Ka.atan((j[3]-j[1])/(j[2]-j[0]))*180/Ka.PI;c=["<",c,' colors="0% ',h,",100% ",n,'" angle="',a,'" opacity="',t,'" o:opacity2="',l,'" type="gradient" focus="100%" />'];Fa(this.prepVML(c),null,null,b)}else if(e.test(a)){d=Kb(a);c=["<",c,' opacity="',d.get("a"),'"/>'];Fa(this.prepVML(c),null,null,b);return d.get("rgb")}else return a},prepVML:function(a){var b=
"display:inline-block;behavior:url(#default#VML);",c=this.isIE8;a=a.join("");if(c){a=a.replace("/>",' xmlns="urn:schemas-microsoft-com:vml" />');a=a.indexOf('style="')==-1?a.replace("/>",' style="'+b+'" />'):a.replace('style="','style="'+b)}else a=a.replace("<","<hcv:");return a},text:function(a,b,c,d,e,f){d=d||{};f=f||"left";e=e||0;var g=W(parseInt(d.fontSize||12,10)*1.2),j=wa.chart.style;b=W(b);c=W(c);R(d,{color:d.color||"#000000",whiteSpace:"nowrap",fontFamily:d.fontFamily||j.fontFamily,fontSize:d.fontSize||
j.fontSize});if(e){j=(e||0)*Ka.PI*2/360;e=Ib(j);j=Jb(j);var h=10;g=g*0.3;var l=f=="left",n=f=="right",t=l?b:b-h*e;b=n?b:b+h*e;l=l?c:c-h*j;c=n?c:c+h*j;t+=g*j;b+=g*j;l-=g*e;c-=g*e;if(Ya(t-b)<0.1)t+=0.1;if(Ya(l-c)<0.1)l+=0.1;c=this.createElement("line").attr({from:t+", "+l,to:b+", "+c});e=c.element;Fa("hcv:fill",{on:true,color:d.color},null,e);Fa("hcv:path",{textpathok:true},null,e);Fa('<hcv:textpath style="v-text-align:'+f+";"+oc(d).replace(/"/g,"'")+'" on="true" string="'+a.toString().replace(/<br[^>]?>/g,
"\n")+'">',null,null,e)}else{c=this.createElement("span").attr({x:b,y:c-g,text:a});e=c.element;e.lineHeight=g;Na(e,d);if(f!="left"){a=c.getBBox().width;Na(e,{left:b-a/{right:1,center:2}[f]+Da})}}return c},path:function(a){return this.createElement("shape").attr({coordsize:"100 100",d:a})},circle:function(a,b,c){return this.path(this.symbols.circle(a,b,c))},g:function(a){var b;if(a)b={className:Gb+a,"class":Gb+a};return a=this.createElement(zb).attr(b)},image:function(a,b,c,d,e){return this.createElement("img").attr({src:a}).css({left:b,
top:c,width:d,height:e})},rect:function(a,b,c,d,e,f){if(arguments.length>1){var g=(f||0)%2/2;a=W(a||0)+g;b=W(b||0)+g;c=W((c||0)-2*g);d=W((d||0)-2*g)}if(typeof a=="object"){b=a.y;c=a.width;d=a.height;e=a.r;a=a.x}return this.symbol("rect",a||0,b||0,e||0,{width:c||0,height:d||0})},symbol:function(a,b,c){var d;d=/^url\((.*?)\)$/;return d=d.test(a)?this.createElement("img").attr({onload:function(){var e=this,f=[e.width,e.height];Na(e,{left:W(b-f[0]/2),top:W(c-f[1]/2)})},src:a.match(d)[1]}):Vb.prototype.symbol.apply(this,
arguments)},symbols:{arc:function(a,b,c,d){var e=d.start,f=d.end,g=f-e==2*Math.PI?f-0.0010:f,j=Ib(e),h=Jb(e),l=Ib(g);g=Jb(g);d=d.innerR;if(f-e===0)return["x"];return["wa",a-c,b-c,a+c,b+c,a+c*j,b+c*h,a+c*l,b+c*g,"at",a-d,b-d,a+d,b+d,a+d*l,b+d*g,a+d*j,b+d*h,"x","e"]},circle:function(a,b,c){return["wa",a-c,b-c,a+c,b+c,a+c,b,a+c,b,"e"]},rect:function(a,b,c,d){var e=d.width;d=d.height;var f=a+e,g=b+d;c=Lb(c,e,d);return[$a,a+c,b,Ja,f-c,b,"wa",f-2*c,b,f,b+2*c,f-c,b,f,b+c,Ja,f,g-c,"wa",f-2*c,g-2*c,f,g,f,
g-c,f-c,g,Ja,a+c,g,"wa",a,g-2*c,a+2*c,g,a+c,g,a,g-c,Ja,a,b+c,"wa",a,b,a+2*c,b+2*c,a,b+c,a+c,b,"x","e"]}}})}var bd=Mc?Vb:Nc,Xb=function(){};Xb.prototype={init:function(a,b){var c=this;c.series=a;c.applyOptions(b);c.pointAttr={};if(a.options.colorByPoint){a=a.chart.options.colors;if(!c.options)c.options={};c.color=c.options.color=c.color||a[sb++];if(sb>=a.length)sb=0}return c},applyOptions:function(a){var b=this,c=b.series;b.config=a;if(typeof a=="number"||a===null)b.y=a;else if(typeof a=="object"&&
typeof a.length!="number"){R(b,a);b.options=a}else if(typeof a[0]=="string"){b.name=a[0];b.y=a[1]}else if(typeof a[0]=="number"){b.x=a[0];b.y=a[1]}if(b.x===Ma)b.x=c.autoIncrement()},destroy:function(){var a=this,b;a==a.series.chart.hoverPoint&&a.onMouseOut();Hb(a);o(["dataLabel","graphic","tracker","group"],function(c){a[c]&&a[c].destroy()});a.legendItem&&a.series.chart.legend.destroyItem(a);for(b in a)a[b]=null},select:function(a,b){var c=this,d=c.series;d=d.chart;c.selected=a=z(a,!c.selected);c.firePointEvent(a?
"select":"unselect");c.setState(yb);b||o(d.getSelectedPoints(),function(e){if(e.selected&&e!=c){e.selected=false;e.setState(La);e.firePointEvent("unselect")}})},onMouseOver:function(){var a=this,b=a.series.chart,c=b.tooltip,d=b.hoverPoint;d&&d!=a&&d.onMouseOut();a.firePointEvent("mouseOver");c&&c.refresh(a);a.setState(ob);b.hoverPoint=a},onMouseOut:function(){var a=this;a.firePointEvent("mouseOut");a.setState(La);a.series.chart.hoverPoint=null},update:function(a,b){var c=this,d=c.series;b=z(b,true);
c.firePointEvent("update",{options:a},function(){c.applyOptions(a);d.isDirty=true;b&&d.chart.redraw()})},remove:function(a){var b=this,c=b.series,d=c.chart,e=c.data,f=e.length;a=z(a,true);b.firePointEvent("remove",null,function(){for(;f--;)if(e[f]==b){e.splice(f,1);break}b.destroy();c.isDirty=true;a&&d.redraw()})},firePointEvent:function(a,b,c){var d=this,e=this.series;e=e.options;if(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])this.importEvents();if(a=="click"&&e.allowPointSelect)c=
function(f){d.select(null,f.ctrlKey||f.metaKey||f.shiftKey)};Aa(this,a,b,c)},importEvents:function(){if(!this.hasImportedEvents){var a=this,b=ma(a.series.options.point,a.options);b=b.events;var c;a.events=b;for(c in b)kb(a,c,b[c]);this.hasImportedEvents=true}},setState:function(a){var b=this,c=b.series,d=c.options.states,e=c.options.marker,f=e&&!e.enabled,g=(e=e&&e.states[a])&&e.enabled===false,j=c.chart,h=b.pointAttr;a||(a=La);if(!(b.selected&&a!=yb||d[a]&&d[a].enabled===false||a&&(g||f&&!e.enabled)))if(a&&
!b.graphic){if(!c.stateMarkerGraphic)c.stateMarkerGraphic=j.renderer.circle(0,0,h[a].r).attr(h[a]).add(c.group);c.stateMarkerGraphic.translate(b.plotX,b.plotY)}else b.graphic&&b.graphic.attr(h[a])},setTooltipText:function(){var a=this;a.tooltipText=a.series.chart.options.tooltip.formatter.call({series:a.series,point:a,x:a.category,y:a.y,percentage:a.percentage,total:a.total||a.stackTotal})}};var Sa=function(){};Sa.prototype={isCartesian:true,type:"line",pointClass:Xb,pointAttrToOptions:{stroke:"lineColor",
"stroke-width":"lineWidth",fill:"fillColor",r:"radius"},init:function(a,b){var c=this,d,e=a.series.length;c.chart=a;b=c.setOptions(b);R(c,{index:e,options:b,name:b.name||"Series "+(e+1),state:La,pointAttr:{},visible:b.visible!==false,selected:b.selected===true});a=b.events;for(d in a)kb(c,d,a[d]);c.getColor();c.getSymbol();c.setData(b.data,false)},autoIncrement:function(){var a=this,b=a.options,c=a.xIncrement;c=z(c,b.pointStart,0);a.pointInterval=z(a.pointInterval,b.pointInterval,1);a.xIncrement=
c+a.pointInterval;return c},cleanData:function(){var a=this;a=a.data;var b;a.sort(function(c,d){return c.x-d.x});for(b=a.length-1;b>=0;b--)a[b-1]&&a[b-1].x==a[b].x&&a.splice(b-1,1)},getSegments:function(){var a=-1,b=[],c=this.data;o(c,function(d,e){if(d.y===null){e>a+1&&b.push(c.slice(a+1,e));a=e}else e==c.length-1&&b.push(c.slice(a+1,e+1))});this.segments=b},setOptions:function(a){var b=this.chart.options.plotOptions;return a=ma(b[this.type],b.series,a)},getColor:function(){var a=this.chart.options.colors;
this.color=this.options.color||a[sb++]||"#0000ff";if(sb>=a.length)sb=0},getSymbol:function(){var a=this.chart.options.symbols,b=this.options.marker.symbol||a[kc++];this.symbol=b;if(kc>=a.length)kc=0},addPoint:function(a,b,c){var d=this,e=d.data;a=(new d.pointClass).init(d,a);b=z(b,true);e.push(a);c&&e[0].remove(false);d.isDirty=true;b&&d.chart.redraw()},setData:function(a,b){var c=this,d=c.data,e=c.initialColor,f=d&&d.length||0;c.xIncrement=null;if(T(e))sb=e;for(a=Fb(nc(a||[]),function(g){return(new c.pointClass).init(c,
g)});f--;)d[f].destroy();c.data=a;c.cleanData();c.getSegments();c.isDirty=true;z(b,true)&&c.chart.redraw()},remove:function(a){var b=this,c=b.chart;a=z(a,true);if(!b.isRemoving){b.isRemoving=true;Aa(b,"remove",null,function(){b.destroy();c.isDirty=true;a&&c.redraw()})}b.isRemoving=false},translate:function(){for(var a=this,b=a.chart,c=a.options.stacking,d=a.xAxis.categories,e=a.yAxis,f=e.stacks[a.type],g=a.data,j=g.length;j--;){var h=g[j],l=h.x,n=h.y,t;h.plotX=a.xAxis.translate(l);if(c&&a.visible&&
f[l]){t=f[l];l=t.total;t.cum=t=t.cum-n;n=t+n;if(c=="percent"){t=l?t*100/l:0;n=l?n*100/l:0}h.percentage=l?h.y*100/l:0;h.stackTotal=l;h.yBottom=e.translate(t,0,1)}if(n!==null)h.plotY=e.translate(n,0,1);h.clientX=b.inverted?b.plotHeight-h.plotX:h.plotX;h.category=d&&d[h.x]!==Ma?d[h.x]:h.x}},setTooltipPoints:function(a){var b=this,c=b.chart,d=c.inverted,e=[],f=(d?c.plotTop:c.plotLeft)+c.plotSizeX,g,j,h=[];if(a)b.tooltipPoints=null;o(b.segments,function(l){e=e.concat(l)});if(b.xAxis&&b.xAxis.reversed)e=
e.reverse();o(e,function(l,n){b.tooltipPoints||l.setTooltipText();g=e[n-1]?e[n-1].high+1:0;for(j=l.high=e[n+1]?ib((l.plotX+(e[n+1]?e[n+1].plotX:f))/2):f;g<=j;)h[d?f-g++:g++]=l});b.tooltipPoints=h},onMouseOver:function(){var a=this,b=a.chart,c=b.hoverSeries,d=a.stateMarkerGraphic;if(!b.mouseIsDown){d&&d.show();c&&c!=a&&c.onMouseOut();a.options.events.mouseOver&&Aa(a,"mouseOver");a.tracker&&a.tracker.toFront();a.setState(ob);b.hoverSeries=a}},onMouseOut:function(){var a=this,b=a.options,c=a.chart,d=
c.tooltip,e=c.hoverPoint;e&&e.onMouseOut();a&&b.events.mouseOut&&Aa(a,"mouseOut");d&&!b.stickyTracking&&d.hide();a.setState();c.hoverSeries=null},animate:function(a){var b=this,c=b.chart,d=b.clipRect;if(a){if(!d.isAnimating){d.attr("width",0);d.isAnimating=true}}else{d.animate({width:c.plotSizeX},{complete:function(){d.isAnimating=false},duration:1E3});this.animate=null}},drawPoints:function(){var a=this,b,c=a.data,d=a.chart,e,f,g,j,h,l;if(a.options.marker.enabled)for(g=c.length;g--;){j=c[g];e=j.plotX;
f=j.plotY;l=j.graphic;if(f!==Ma){b=j.pointAttr[j.selected?yb:La];h=b.r;if(l)l.attr({x:e,y:f,r:h});else j.graphic=d.renderer.symbol(z(j.marker&&j.marker.symbol,a.symbol),e,f,h).attr(b).add(a.group)}}},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,j={};a=a||{};b=b||{};c=c||{};d=d||{};for(f in e){g=e[f];j[f]=z(a[g],b[f],c[f],d[f])}return j},getAttribs:function(){var a=this,b=a.options.marker||a.options,c=b.states,d=c[ob],e,f={},g=a.color,j=a.data,h=[],l,n=a.pointAttrToOptions;if(a.options.marker){f=
{stroke:g,fill:g};d.radius=d.radius||b.radius+2;d.lineWidth=d.lineWidth||b.lineWidth+1}else{f={fill:g};d.color=d.color||Kb(d.color||g).brighten(d.brightness).get()}h[La]=a.convertAttribs(b,f);o([ob,yb],function(A){h[A]=a.convertAttribs(c[A],h[La])});a.pointAttr=h;for(f=j.length;f--;){g=j[f];if((b=g.options&&g.options.marker||g.options)&&b.enabled===false)b.radius=0;e=false;if(g.options)for(var t in n)if(T(b[n[t]]))e=true;if(e){l=[];c=b.states||{};e=c[ob]=c[ob]||{};if(!a.options.marker)e.color=Kb(e.color||
g.options.color).brighten(e.brightness||d.brightness).get();l[La]=a.convertAttribs(b,h[La]);l[ob]=a.convertAttribs(c[ob],h[ob],l[La]);l[yb]=a.convertAttribs(c[yb],h[yb],l[La])}else l=h;g.pointAttr=l}},destroy:function(){var a=this,b=a.chart,c=b.series,d=a.clipRect,e;Hb(a);a.legendItem&&a.chart.legend.destroyItem(a);o(a.data,function(f){f.destroy()});o(["area","graph","dataLabelsGroup","group","tracker"],function(f){a[f]&&a[f].destroy()});d&&d!=a.chart.clipRect&&d.destroy();if(b.hoverSeries==a)b.hoverSeries=
null;o(c,function(f,g){f==a&&c.splice(g,1)});for(e in a)delete a[e]},drawDataLabels:function(){if(this.options.dataLabels.enabled){var a=this,b,c,d=a.data,e=a.options.dataLabels,f,g=a.dataLabelsGroup,j=a.chart,h=j.inverted,l=a.type,n,t;if(!g)g=a.dataLabelsGroup=j.renderer.g(Gb+"data-labels").attr({visibility:a.visible?Wb:xb,zIndex:4}).translate(j.plotLeft,j.plotTop).add();n=e.color;if(n=="auto")n=null;e.style.color=z(n,a.color);o(d,function(A){var F=z(A.barX,A.plotX),da=A.plotY,X=A.tooltipPos,O=A.dataLabel;
if(O)A.dataLabel=O.destroy();f=e.formatter.call({x:A.x,y:A.y,series:a,point:A,percentage:A.percentage,total:A.total||A.stackTotal});b=(h?j.plotWidth-da:F)+e.x;c=(h?j.plotHeight-F:da)+e.y;if(X){b=X[0]+e.x;c=X[1]+e.y}t=e.align;if(l=="column")b+={center:A.barW/2,right:A.barW}[t]||0;if(f)A.dataLabel=j.renderer.text(f,b,c,e.style,e.rotation,t).attr({zIndex:1,visibility:A.visible===false?xb:"inherit"}).add(g);a.drawConnector&&a.drawConnector(A)})}},drawGraph:function(){var a=this,b=a.options,c=a.chart,
d=a.graph,e=[],f=a.area,g=a.group,j=b.lineColor||a.color,h=b.lineWidth,l;c=c.renderer;var n=a.yAxis.getThreshold(b.threshold||0),t=/^area/.test(a.type),A=[],F=[];o(a.segments,function(da){if(da.length>1){l=[];o(da,function(db,eb){eb<2&&l.push([$a,Ja][eb]);if(eb&&b.step){eb=da[eb-1];l.push(db.plotX,eb.plotY)}l.push(db.plotX,db.plotY)});e=e.concat(l);if(t){var X=[],O,rb=l.length;for(O=0;O<rb;O++)X.push(l[O]);if(b.stacking&&a.type!="areaspline")for(O=da.length-1;O>=0;O--)X.push(da[O].plotX,da[O].yBottom);
else X.push(da[da.length-1].plotX,n,da[0].plotX,n,"z");F=F.concat(X)}}else A.push(da[0])});a.graphPath=e;a.singlePoints=A;if(d)d.attr({d:e});else if(h)a.graph=c.path(e).attr({stroke:j,"stroke-width":h+Da}).add(g).shadow(b.shadow);if(t){d=z(b.fillColor,Kb(a.color).setOpacity(b.fillOpacity||0.75).get());if(f)f.attr({d:F});else a.area=a.chart.renderer.path(F).attr({fill:d}).add(a.group)}},render:function(){var a=this,b=a.chart,c,d=a.options.animation&&a.animate;c=b.renderer;if(!a.clipRect){a.clipRect=
!b.hasRendered&&b.clipRect?b.clipRect:c.clipRect(0,0,b.plotSizeX,b.plotSizeY);if(!b.clipRect)b.clipRect=a.clipRect}if(!a.group){c=a.group=c.g("series");b.inverted&&c.attr({width:b.plotWidth,height:b.plotHeight}).invert();c.clip(a.clipRect).attr({visibility:a.visible?Wb:xb,zIndex:3}).translate(b.plotLeft,b.plotTop).add()}a.drawDataLabels();d&&a.animate(true);a.getAttribs();a.drawGraph&&a.drawGraph();a.drawPoints();a.options.enableMouseTracking!==false&&a.drawTracker();d&&a.animate();a.isDirty=false},
redraw:function(){var a=this;a.translate();a.setTooltipPoints(true);a.render()},setState:function(a){var b=this,c=b.options,d=b.graph,e=c.states,f=b.stateMarkerGraphic;c=c.lineWidth;a=a||La;if(b.state!=a){b.state=a;if(!(e[a]&&e[a].enabled===false)){if(a)c=e[a].lineWidth||c;else f&&f.hide();if(d)d.animate({"stroke-width":c},a?0:500)}}},setVisible:function(a,b){var c=this,d=c.chart,e=c.legendItem,f=c.group,g=c.tracker,j=c.dataLabelsGroup,h,l=c.data,n=d.options.chart.ignoreHiddenSeries;h=c.visible;h=
(c.visible=a=a===Ma?!h:a)?"show":"hide";if(a)c.isDirty=n;f&&f[h]();if(g)g[h]();else for(f=l.length;f--;){g=l[f];g.tracker&&g.tracker[h]()}j&&j[h]();e&&d.legend.colorizeItem(c,a);n&&c.options.stacking&&o(d.series,function(t){if(t.options.stacking&&t.visible)t.isDirty=true});b!==false&&d.redraw();Aa(c,h)},show:function(){this.setVisible(true)},hide:function(){this.setVisible(false)},select:function(a){var b=this;b.selected=a=a===Ma?!b.selected:a;if(b.checkbox)b.checkbox.checked=a;Aa(b,a?"select":"unselect")},
drawTracker:function(){var a=this,b=a.options,c=a.graphPath,d=a.chart,e=d.options.tooltip.snap,f=a.tracker,g=b.cursor;g=g&&{cursor:g};var j=a.singlePoints,h,l;for(l=0;l<j.length;l++){h=j[l];c.push($a,h.plotX-3,h.plotY,Ja,h.plotX+3,h.plotY)}if(f)f.attr({d:c});else a.tracker=d.renderer.path(c).attr({isTracker:true,stroke:ed,fill:fb,"stroke-width":b.lineWidth+2*e,"stroke-linecap":"round",visibility:a.visible?Wb:xb,zIndex:1}).on("mouseover",function(){d.hoverSeries!=a&&a.onMouseOver()}).on("mouseout",
function(){b.stickyTracking||a.onMouseOut()}).css(g).add(d.trackerGroup)}};ra=gb(Sa);cb.line=ra;ra=gb(Sa,{type:"area"});cb.area=ra;dd.prototype={get:function(a){a||(a=50);var b=this.n;b=(this.xdata[b-1]-this.xdata[0])/(a-1);var c=[],d=[];c[0]=this.xdata[0];d[0]=this.ydata[0];for(var e=[{plotX:c[0],plotY:d[0]}],f=1;f<a;f++){c[f]=c[0]+f*b;d[f]=this.interpolate(c[f]);e[f]={plotX:c[f],plotY:d[f]}}return e},interpolate:function(a){for(var b=this.n-1,c=0;b-c>1;){var d=(b+c)/2;if(this.xdata[ib(d)]>a)b=d;
else c=d}b=ib(b);c=ib(c);d=this.xdata[b]-this.xdata[c];var e=(this.xdata[b]-a)/d;a=(a-this.xdata[c])/d;return e*this.ydata[c]+a*this.ydata[b]+((e*e*e-e)*this.y2[c]+(a*a*a-a)*this.y2[b])*d*d/6}};ra=gb(Sa,{type:"spline",drawGraph:function(){var a=this,b=a.segments;a.splinedata=a.getSplineData();a.segments=a.splinedata;Sa.prototype.drawGraph.apply(a,arguments);a.segments=b},getSplineData:function(){var a=this,b=a.chart,c=[],d=b.plotSizeX,e;o(a.segments,function(f){if(a.xAxis.reversed)f=f.reverse();var g=
[],j,h;o(f,function(l,n){j=f[n+2]||f[n+1]||l;h=f[n-2]||f[n-1]||l;j.plotX>=0&&h.plotX<=d&&g.push(l)});if(g.length>1)e=W(tb(d,g[g.length-1].clientX-g[0].clientX)/3);c.push(f.length>1?e?(new dd(g)).get(e):[]:f)});return c}});cb.spline=ra;ra=gb(ra,{type:"areaspline"});cb.areaspline=ra;var mc=gb(Sa,{type:"column",pointAttrToOptions:{stroke:"borderColor","stroke-width":"borderWidth",fill:"color",r:"borderRadius"},init:function(){Sa.prototype.init.apply(this,arguments);var a=this,b=a.chart;b.hasRendered&&
o(b.series,function(c){if(c.type==a.type)c.isDirty=true})},translate:function(){var a=this,b=a.chart,c=0,d=a.xAxis.reversed,e=a.xAxis.categories,f;Sa.prototype.translate.apply(a);o(b.series,function(X){if(X.type==a.type)if(X.options.stacking){T(f)||(f=c++);X.columnIndex=f}else X.columnIndex=c++});var g=a.options,j=a.data,h=a.closestPoints;b=Ya(j[1]?j[h].plotX-j[h-1].plotX:b.plotSizeX/(e?e.length:1));e=b*g.groupPadding;h=b-2*e;h=h/c;var l=g.pointWidth,n=T(l)?(h-l)/2:h*g.pointPadding,t=z(l,h-2*n);l=
(d?c-a.columnIndex:a.columnIndex)||0;var A=n+(e+l*h-b/2)*(d?-1:1),F=a.yAxis.getThreshold(g.threshold||0),da=g.minPointLength;o(j,function(X){var O=X.plotY,rb=X.plotX+A,db=vc(Lb(O,F)),eb=t,G=vc(Ya((X.yBottom||F)-O)),va;if(Ya(G)<(da||5)){if(da){G=da;db=F-(O<=F?da:0)}va=db-3}R(X,{barX:rb,barY:db,barW:eb,barH:G});X.shapeType="rect";X.shapeArgs={x:rb,y:db,width:eb,height:G,r:g.borderRadius};X.trackerArgs=T(va)&&ma(X.shapeArgs,{height:6,y:va})})},getSymbol:function(){},drawGraph:function(){},drawPoints:function(){var a=
this,b=a.options,c=a.chart.renderer,d,e;o(a.data,function(f){if(T(f.plotY)){d=f.graphic;e=f.shapeArgs;if(d)d.attr(e);else f.graphic=c[f.shapeType](e).attr(f.pointAttr[f.selected?yb:La]).add(a.group).shadow(b.shadow)}})},drawTracker:function(){var a=this,b=a.chart,c=b.renderer,d,e,f=+new Date,g=a.options.cursor,j=g&&{cursor:g},h;o(a.data,function(l){e=l.tracker;d=l.trackerArgs||l.shapeArgs;if(e)e.attr(d);else l.tracker=c[l.shapeType](d).attr({isTracker:f,fill:ed,visibility:a.visible?Wb:xb,zIndex:1}).on("mouseover",
function(n){h=n.relatedTarget||n.fromElement;b.hoverSeries!=a&&pa(h,"isTracker")!=f&&a.onMouseOver();l.onMouseOver()}).on("mouseout",function(n){if(!a.options.stickyTracking){h=n.relatedTarget||n.toElement;pa(h,"isTracker")!=f&&a.onMouseOut()}}).css(j).add(b.trackerGroup)})},cleanData:function(){var a=this,b=a.data,c,d,e,f;Sa.prototype.cleanData.apply(a);for(f=b.length-1;f>=0;f--)if(b[f-1]){c=b[f].x-b[f-1].x;if(d===Ma||c<d){d=c;e=f}}a.closestPoints=e},animate:function(a){var b=this,c=b.data;if(!a){o(c,
function(d){var e=d.graphic;if(e){e.attr({height:0,y:b.yAxis.translate(0,0,1)});e.animate({height:d.barH,y:d.barY},{duration:1E3})}});b.animate=null}},remove:function(){var a=this,b=a.chart;b.hasRendered&&o(b.series,function(c){if(c.type==a.type)c.isDirty=true});Sa.prototype.remove.apply(a,arguments)}});cb.column=mc;ra=gb(mc,{type:"bar",init:function(a){a.inverted=this.inverted=true;mc.prototype.init.apply(this,arguments)}});cb.bar=ra;ra=gb(Sa,{type:"scatter",translate:function(){var a=this;Sa.prototype.translate.apply(a);
o(a.data,function(b){b.shapeType="circle";b.shapeArgs={x:b.plotX,y:b.plotY,r:a.chart.options.tooltip.snap}})},drawTracker:function(){var a=this,b=a.options.cursor,c=b&&{cursor:b},d;o(a.data,function(e){(d=e.graphic)&&d.attr({isTracker:true}).on("mouseover",function(){a.onMouseOver();e.onMouseOver()}).on("mouseout",function(){a.options.stickyTracking||a.onMouseOut()}).css(c)})},cleanData:function(){}});cb.scatter=ra;ra=gb(Xb,{init:function(){Xb.prototype.init.apply(this,arguments);var a=this,b;R(a,
{visible:a.visible!==false,name:z(a.name,"Slice")});b=function(){a.slice()};kb(a,"select",b);kb(a,"unselect",b);return a},setVisible:function(a){var b=this,c=b.series.chart,d;d=(b.visible=a=a===Ma?!b.visible:a)?"show":"hide";b.group[d]();b.tracker&&b.tracker[d]();b.dataLabel&&b.dataLabel[d]();b.legendItem&&c.legend.colorizeItem(b,a)},slice:function(a,b){var c=this,d=c.series;d=d.chart;var e=c.slicedTranslation;z(b,true);a=c.sliced=T(a)?a:!c.sliced;c.group.animate({translateX:a?e[0]:d.plotLeft,translateY:a?
e[1]:d.plotTop},100)}});ra=gb(Sa,{type:"pie",isCartesian:false,pointClass:ra,pointAttrToOptions:{stroke:"borderColor","stroke-width":"borderWidth",fill:"color"},getColor:function(){this.initialColor=sb},translate:function(){var a=0,b=this,c=-0.25,d=b.options,e=d.slicedOffset,f=d.center,g=b.chart,j=g.plotWidth,h=g.plotHeight,l,n,t;b=b.data;var A=2*Ka.PI,F,da=Lb(j,h),X;f.push(d.size,d.innerSize||0);f=Fb(f,function(O,rb){return(X=/%$/.test(O))?[j,h,da,da][rb]*parseInt(O,10)/100:O});o(b,function(O){a+=
O.y});o(b,function(O){F=a?O.y/a:0;l=c*A;c+=F;n=c*A;O.shapeType="arc";O.shapeArgs={x:f[0],y:f[1],r:f[2]/2,innerR:f[3]/2,start:l,end:n};t=(n+l)/2;O.slicedTranslation=Fb([Ib(t)*e+g.plotLeft,Jb(t)*e+g.plotTop],W);O.tooltipPos=[f[0]+Ib(t)*f[2]*0.35,f[1]+Jb(t)*f[2]*0.35];O.percentage=F*100;O.total=a});this.setTooltipPoints()},render:function(){var a=this;a.getAttribs();this.drawPoints();a.options.enableMouseTracking!==false&&a.drawTracker();this.drawDataLabels();a.isDirty=false},drawPoints:function(){var a=
this,b=a.chart,c=b.renderer,d,e,f;o(a.data,function(g){e=g.graphic;f=g.shapeArgs;if(!g.group){d=g.sliced?g.slicedTranslation:[b.plotLeft,b.plotTop];g.group=c.g("point").attr({zIndex:3}).add().translate(d[0],d[1])}if(e)e.attr(f);else g.graphic=c.arc(f).attr(g.pointAttr[La]).add(g.group);g.visible===false&&g.setVisible(false)})},drawTracker:mc.prototype.drawTracker,getSymbol:function(){}});cb.pie=ra;lb.Highcharts={Chart:jd,dateFormat:hc,getOptions:gd,numberFormat:hd,Point:Xb,Renderer:bd,seriesTypes:cb,
setOptions:fd,Series:Sa,addEvent:kb,createElement:Fa,discardElement:bc,css:Na,each:o,extend:R,map:Fb,merge:ma,pick:z,extendClass:gb}})();
