//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.08 at 08:37:26 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gtwm.com/jasperexecute/runJasperReports", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gtwm.jasperexecute.beans;
