//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b24-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.01.08 at 08:37:26 PM CET 
//


package com.gtwm.jasperexecute.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobsReports complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobsReports">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailSubject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailFrom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailToList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emailTemplate" type="{http://www.gtwm.com/jasperexecute/runJasperReports}EmailTemplate"/>
 *         &lt;element name="Sources" type="{http://www.gtwm.com/jasperexecute/runJasperReports}DataSources"/>
 *         &lt;element name="Reports" type="{http://www.gtwm.com/jasperexecute/runJasperReports}Reports"/>
 *         &lt;element name="mailSmtp" type="{http://www.gtwm.com/jasperexecute/runJasperReports}SmtpServer" minOccurs="0"/>
 *         &lt;element name="outputFolder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobsReports", propOrder = {
    "name",
    "emailSubject",
    "emailFrom",
    "emailToList",
    "emailTemplate",
    "sources",
    "reports",
    "mailSmtp",
    "outputFolder"
})
public class JobsReports {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String emailSubject;
    @XmlElement(required = true)
    protected String emailFrom;
    @XmlElement(required = true)
    protected String emailToList;
    @XmlElement(required = true)
    protected EmailTemplate emailTemplate;
    @XmlElement(name = "Sources", required = true)
    protected DataSources sources;
    @XmlElement(name = "Reports", required = true)
    protected Reports reports;
    protected SmtpServer mailSmtp;
    @XmlElement(required = true)
    protected String outputFolder;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the emailSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailSubject() {
        return emailSubject;
    }

    /**
     * Sets the value of the emailSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailSubject(String value) {
        this.emailSubject = value;
    }

    /**
     * Gets the value of the emailFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailFrom() {
        return emailFrom;
    }

    /**
     * Sets the value of the emailFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailFrom(String value) {
        this.emailFrom = value;
    }

    /**
     * Gets the value of the emailToList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailToList() {
        return emailToList;
    }

    /**
     * Sets the value of the emailToList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailToList(String value) {
        this.emailToList = value;
    }

    /**
     * Gets the value of the emailTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link EmailTemplate }
     *     
     */
    public EmailTemplate getEmailTemplate() {
        return emailTemplate;
    }

    /**
     * Sets the value of the emailTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailTemplate }
     *     
     */
    public void setEmailTemplate(EmailTemplate value) {
        this.emailTemplate = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link DataSources }
     *     
     */
    public DataSources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSources }
     *     
     */
    public void setSources(DataSources value) {
        this.sources = value;
    }

    /**
     * Gets the value of the reports property.
     * 
     * @return
     *     possible object is
     *     {@link Reports }
     *     
     */
    public Reports getReports() {
        return reports;
    }

    /**
     * Sets the value of the reports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reports }
     *     
     */
    public void setReports(Reports value) {
        this.reports = value;
    }

    /**
     * Gets the value of the mailSmtp property.
     * 
     * @return
     *     possible object is
     *     {@link SmtpServer }
     *     
     */
    public SmtpServer getMailSmtp() {
        return mailSmtp;
    }

    /**
     * Sets the value of the mailSmtp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmtpServer }
     *     
     */
    public void setMailSmtp(SmtpServer value) {
        this.mailSmtp = value;
    }

    /**
     * Gets the value of the outputFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFolder() {
        return outputFolder;
    }

    /**
     * Sets the value of the outputFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFolder(String value) {
        this.outputFolder = value;
    }

}
